apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container-1
        image: nginx:alpine
        ports:
        - containerPort: 80
      - name: container-2
        image: tomcat:alpine
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: my-app  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector:
    app: my-app  
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30893
