apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-nginx
spec:
  selector:
    matchLabels:
      run: maintenance-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: maintenance-nginx
    spec:
      containers:
        - image: mayurtannirwar/static-web-image:project
          name: maintenance-nginx
          ports:
            - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: maintenance-nginx
  labels:
    run: maintenance-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: LoadBalancer
  selector:
    run: maintenance-nginx
